baseURL = "https://digitalcloudnw.com"
title = "Digital Cloud"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = false

canonifyURLs = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsUseClassic = false

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Minimalist theme for Hugo"
title404 = "Page Not Found"

[params]
description = "Site stuff for being a good site with internet tubez."
pagetitle = "Hello"
noindex_kinds = [
  "taxonomy",
  "taxonomyTerm"
]

disableKinds = ["taxonomy", "taxonomyTerm"]

[params.assets]
favicon = "favicon.ico"
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Digital Cloud"
startYear = "2015"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "Jan 02, 2006"
listDateFormat = "Jan 02, 2006"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true

disqusShortname = "jhausotter"

[params.opengraph.twitter]
page = "staywyld" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = ""
# instagram = "digitalcloudnw"
# facebook = "digitalcloudnw"

[params.social.config]
platforms = ["instagram","email"]

# [taxonomies]
#   author = "authors"
#   category = "categories"
#   tag = "tags"

# [taxonomies]
#     category = "categories"
#     tag = "tags"

[permalinks]
page = "/:slug/"

# [[menu.main]]
# name = "Services"
# weight = 1
# identifier = "Services"
# url = "#"

[[menu.main]]
name = "Web Design"
weight = 1
identifier = "Web Design"
url = "web-design/"
# parent = "Services"

[[menu.main]]
name = "Web Development"
weight = 2
identifier = "Web Development"
url = "web-development/"
# parent = "Services"

[[menu.main]]
name = "Local SEO"
weight = 3
identifier = "Local SEO"
url = "local-seo/"
# parent = "Services"

# [[menu.main]]
# name = "Portfolio"
# weight = 3
# identifier = "Portfolio"
# url = "portfolio"

# [[menu.main]]
# name = "About"
# weight = 4
# identifier = "About"
# url = "about"

# [[menu.main]]
# name = "Blog"
# weight = 5
# identifier = "Blog"
# url = "blog"

[[menu.main]]
name = "Contact"
weight = 6
identifier = "Contact"
class = "contact"
url = "contact/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
